config/routes.rb
Rails.application.routes.draw do
  root 'index#top'
  get 'admin_top', to:'admin#top', as:'admin_top'
  get 'user_top', to:'user#top', as:'user_top'
  post 'user_new', to:'user#new', as:'user_new'
  post 'user_login', to:'user#login', as:'user_login'
  get 'user_logout', to:'user#logout', as:'user_logout'
  post 'item_add', to:'admin#add', as:'item_add'
  post 'cart_add', to:'user#cart_add', as:'cart_add'
  get 'user_login_top', to:'user#login_top', as:'user_login_top'
  get 'cart_show', to: 'user#cart_show', as:'cart_show'
  #post 'admin_item_add', to:'admin#add', as:'admin_item_top'
  post 'cart_destroy', to:'user#cart_destroy', as:'cart_destroy'
  post 'cart_update', to:'user#cart_update', as:'cart_update'
  post 'buy', to:'user#buy', as:'buy'
  #get 'index/top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :user, foreign_key: :user_id	
    belongs_to :item, foreign_key: :item_id
    #has_many :items
    #has_many :users
end

app/models/item.rb
class Item < ApplicationRecord
    #mount_uploader :item_image, ImageUploader
    has_many :carts
    #belongs_to :cart, foreign_key: :item_id
end

app/models/user.rb
class User < ApplicationRecord
    #belongs_to :cart, foreign_key: :user_id
    has_many :carts
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def top
    @users = User.all
    @items  = Item.all
    @item = Item.new
  end
  def add
    @item = Item.new(item_name:params[:item_name], item_price:params[:item_price], item_stock:params[:item_stock], item_img:'1.jpg')
    @item.save
    redirect_to admin_top_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def top
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def top
    @user = User.new
  end
  def new
    @user = User.new(name:params[:name], mail:params[:mail], password:params[:password])
    @user.save
    redirect_to user_top_path
  end
  def login
    @user = User.find_by(mail:params[:mail], password:params[:password])
    @items = Item.all
    @item = Item.new
    session[:user_id] = @user.id
  end
  def login_top
    @user = User.find_by_id(session[:user_id])
    @items = Item.all
    session[:user_id] = @user.id
  end
  def logout
    session[:user_id] = nil;
    redirect_to user_top_path
  end
  def cart_add
    @cart = Cart.new(user_id:session[:user_id], item_id:params[:item_id], number:params[:number])
    @cart.save
    redirect_to user_login_top_path
  end
  def cart_show
    @carts = Cart.joins(:item).select('carts.id as cart_id, items.id as item_id, items.item_img as item_img, items.item_name as item_name, items.item_price as item_price, items.item_stock as stock, carts.number as number').where('carts.user_id=?', session[:user_id])
    #@carts = Cart.where('user_id = ?', session[:user_id])
  end
  def cart_destroy
    @cart = Cart.find_by_id(params[:cart_id])
    @cart.destroy
    redirect_to user_login_top_path
  end
  def cart_update
    @cart = Cart.find_by_id(params[:cart_id])
    @cart.update(number:params[:number])
    redirect_to user_login_top_path
  end
  def buy
    @carts = Cart.joins(:item).select('carts.id as cart_id, items.id as item_id, items.item_stock as stock, carts.number as number').where('carts.user_id=?', session[:user_id])
    @carts.each do |cart|
      @item = Item.find_by_id(cart.item_id)
      @item.update(item_stock:cart.stock-cart.number)
    end
    @carts = Cart.all.where('user_id = ?', session[:user_id])
    @carts.each do |cart|
      cart.destroy
    end
    redirect_to user_login_top_path
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admin/top.html.erb
<h1>登録会員一覧</h1>
<table>
    <tr>
        <th>ユーザID</th>
        <th>ユーザ名</th>
        <th>メールアドレス</th>
        <th>パスワード</th>
        <th>登録日時</th>
    </tr>
    <% @users.each do |user| %>
    <tr>
        <td><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= user.mail %></td>
        <td><%= user.password %></td>
        <td><%= user.created_at %></td>
    </tr>
    <% end %>
</table>
<h1>商品一覧</h1>
<table>
    <tr>
        <th>商品画像</th>
        <th>商品番号</th>
        <th>商品名</th>
        <th>価格</th>
        <th>在庫</th>
    </tr>
    <% @items.each do |item| %>
    <tr>
        <td><%= image_tag item.item_img %></td>
        <td><%= item.id %></td>
        <td><%= item.item_name %></td>
        <td><%= item.item_price %></td>
        <td><%= item.item_stock %></td>
    </tr>    
    <% end %>
</table>

<h1>新規商品追加</h1>
<%= form_tag("/item_add") do %> 
<!--<form method="post">-->
    <div>商品名：　<input type="text" name="item_name"></div>
    <div>価格：　<input type="text" name="item_price"></div>
    <div>在庫数：　<input type="text" name="item_stock"></div>
    <input type="submit" name="botan" value="商品追加">
<!--</form>-->
<% end %>

<div><%= link_to 'システムトップへ', root_path %></div>

app/views/index/top.html.erb
<h1>簡易ECサイト</h1>
<ul>
    <li><%= link_to '管理者トップへ', admin_top_path %></li>
    <li><%= link_to 'ユーザトップへ', user_top_path %></li>
    
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ec</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/user/cart_show.html.erb
<h1>カート一覧</h1>
<table>
    <tr>
        <th>カート番号</th>
        <th>商品ID</th>
        <th>商品画像</th>
        <th>商品名</th>
        <th>商品単価</th>
        <th>現在の在庫数</th>
        <th>個数</th>
        <th>小計</th>
        <th>削除</th>
    </tr>
    <% @carts.each do |cart| %>
    <tr>
        <td><%= cart.cart_id %></td>
        <td><%= cart.item_id %></td>
        <td><%= image_tag cart.item_img %></td>
        <td><%= cart.item_name %></td>
        <td><%= cart.item_price %>円</td>
        <td><%= cart.stock %>個</td>
        <td>
            <%= form_tag('/cart_update') do %>
                <input type="text" name="number" value="<%= cart.number %>">個
                <input type="hidden" name="cart_id" value="<%= cart.cart_id %>">
                <input type="submit" value="変更">
        </td>
            <% end %>
        <td><%= cart.number * cart.item_price %>円</td>
        <td>
            <!--<from method="post">-->
            <%= form_tag('/cart_destroy') do%>
                <input type="hidden" name="cart_id" value="<%= cart.cart_id %>">
                <input type="submit" value="削除">
            <!--</from>-->
            <% end %>
        </td>
    </tr>
    <% end %>
</table>

<%= form_tag('/buy') do %>
    <input type="submit" value="購入">
<% end %>

<%= link_to '会員トップへ', user_login_top_path %>

app/views/user/login.html.erb
<%= @user.name %>さん、ようこそ！
<%= link_to 'カートへ', cart_show_path %>

<h1>商品一覧</h1>
<table>
    <tr>
        <th>商品画像</th>
        <th>商品番号</th>
        <th>商品名</th>
        <th>価格</th>
        <th>個数</th>
    </tr>
    <% @items.each do |item| %>
    <tr>
        <td><%= image_tag item.item_img %></td>
        <td><%= item.id %></td>
        <td><%= item.item_name %></td>
        <td><%= item.item_price %></td>
        <td>
            <%= form_tag('/cart_add') do %>
            <input type="text" name="number">個
            <input type="hidden" name="item_id" value="<%= item.id %>">
            <input type="submit" value="カートに追加">
            <% end %>
        </td>
    </tr>    
    <% end %>
</table>

<div><%= link_to 'ログアウト', user_logout_path %></div>

app/views/user/login_top.html.erb
<%= @user.name %>さん、ようこそ！
<%= link_to 'カートへ', cart_show_path %>

<h1>商品一覧</h1>
<table>
    <tr>
        <th>商品画像</th>
        <th>商品番号</th>
        <th>商品名</th>
        <th>価格</th>
        <th>個数</th>
    </tr>
    <% @items.each do |item| %>
    <tr>
        <td><%= image_tag item.item_img %></td>
        <td><%= item.id %></td>
        <td><%= item.item_name %></td>
        <td><%= item.item_price %></td>
        <td>
            <%= form_tag('/cart_add') do %>
            <input type="text" name="number">個
            <input type="hidden" name="item_id" value="<%= item.id %>">
            <input type="submit" value="カートに追加">
            <% end %>
        </td>
    </tr>    
    <% end %>
</table>

<div><%= link_to 'ログアウト', user_logout_path %></div>

app/views/user/top.html.erb
<h1>ログイン</h1>
<!--<form method="post" astion="#">-->
<%= form_tag("/user_login") do %> 
    <div>メールアドレス：　<input type="text" name="mail" placeholder="メルアドを入力してください"></div>
    <div>パスワード：　<input type="password" name="password" placeholder="パスワードを入力してください"></div>
    <input type="submit" value="ログイン">
<!--</form>-->
<% end %>

<h1>新規会員登録</h1>
<!--<form method="post" astion="#">-->
<%= form_tag("/user_new") do %> 
    <div>お名前：　<input type="text" name="name" placeholder="メルアドを入力してください"></div>
    <div>メールアドレス：　<input type="text" name="mail" placeholder="メルアドを入力してください"></div>
    <div>パスワード：　<input type="password" name="password" placeholder="パスワードを入力してください"></div>
    <input type="submit" value="登録">
<!--</form>-->
<% end %>

<div><%= link_to 'システムトップへ', root_path %></div>